### ISSUE TITLE
Other mod discrepancies

### ISSUE THREAD

**Issue by dexula** [Roundaround/mc-fabric-armor-stands#9] opened 2023-06-18 07:11 UTC
Mods like [Blur Mod](https://modrinth.com/mod/blur-fabric), [EMI Mod](https://modrinth.com/mod/emi), and [Stylish Effects Mod](https://modrinth.com/mod/stylish-effects) has some kind of issue with the HUD of this mod. I was wondering if there was a way to configure this.

EMI mod looks at it as if it's being treated as an inventory screen. Same with the Stylish Effects mod. I can configure the Blur mod to ignore the Armor Stand Editor screen, though I just don't have a way to figure out the name of the Editor screen UI.

![2023-06-18_00 10 08](https://github.com/Roundaround/mc-fabric-armor-stands/assets/116233696/1a9ee3e2-dfaf-4fe0-ae00-0ad4a5b58e75)

**Comment by agentwolf88** [comment] 2023-06-19 09:13
Same problem!

**Comment by N0aW** [comment] 2023-06-28 15:51
Same problem.

The problem is in Fabric 1.19.4 and Fabric 1.20

**Comment by Roundaround** [comment] 2023-06-29 21:45
For Blur and Stylish Effects, they've added the ability to exclude screens through their respective configs. I've added some instructions to the bottom of the Armor Stands mod page detailing what you need to add: https://modrinth.com/mod/armor-stands

As for EMI, there's not really a good way to integrate. A similar issue (https://github.com/emilyploszaj/emi/issues/205) has been reported on EMI's GitHub, but the answer was basically that EMI does a blanket check for all screens of a certain type, with no way to configure it. Until a configuration mechanic is implemented, unfortunately the two mods will be incompatible.

**Closed by Roundaround** 2023-06-29 21:45 UTC
